
# override these defaults using a local.yaml file
config:
    port: 9002

    logs:
        # see hmpo-logger for config options

    jenkins:
        # credentials: username:password
        baseUrl: https://jenkins.example.com
        saveCache: false
        projectFormat: '{project:alpha}'
        ## promotion environments
        environments:
            stg: stg
            sit: sit
            int: int

    jenkinsOld:
        # credentials: username:password
        baseUrl: https://jenkins.example.com
        saveCache: false
        projectFormat: '{project:alpha}'
        ## promotion environments
        environments:
            stg: stg
            sit: sit
            int: int

    jenkinsPromote:
        # credentials: username:password
        baseUrl: https://jenkins.example.com
        saveCache: false
        projectFormat: '{project:alpha}.yml'
        promoteJob: promote
        promoteLinkArgs: 'PROMOTED_JOB_NAME={project}.yml&ENVIRONMENT={environment}&PROMOTED_NUMBER={releaseId}'
        ## promotion environments
        environments:
            prd: prd

    jira:
        # credentials: username:password
        baseUrl: https://jira.example.com
        saveCache: true
        statusMap:
            'Open': develop
            'Test': test
            'Review': review
            'Resolved': ready
            'Closed': closed

    gitlab:
        # privateToken: ABCDEFG1234567
        baseUrl: https://gitlab.example.com
        saveCache: true
        projectFormat: group-name/{project:alpha}
        ticketsInBody: false

        ## only include projects with these tags in the project list
        projectTags:
            - BUILDSTATUS

        ## list of misspelt jira ticket prefixes to correct
        ticketMatching:
            BAD: GOOD

