
# override these defaults using a local.yaml file
config:
    port: 9002

    logs:
        # see hmpo-logger for config options
        app: false
        error: false
        console: true

    engines:
        all:
            redisCache:
                # see node-redis for config options
            saveCache: false
